name: Dump Pipeline
on:
  [push]
jobs:
  Dump-Database:
    runs-on: linode-vm
    steps:
      - name: Dump database.
        working-directory: /root/source/dumps/
        run: |
         echo ": dumping database"
         docker exec -t portfolio-vm_postgresql_database_1  pg_dumpall -c -U postgres > `date +%Y-%m-%d`.sql
      - name: Delete old dumps.
        working-directory: /root/source/dumps/
        run: |
         f1days=$(date +%s --date="-1 days"); for file in *.sql; do fdate=$(echo $file | tr _ -);fsec=$(date +%s --date=${fdate/.sql/});if [[ $fsec -lt $f1days ]]; then rm $file;fi;done
  Transfer-Dump:
    needs: Dump-Database
    runs-on: snow-backup
    steps:
      - name: Transfer dump.
        working-directory: /home/hector/source/dumps/
        run: |
          echo ": removing old dumps."
          rm -f *
          echo ": turning on VPN."
          sudo wg-quick up wg-hector
          echo ": transfering dump over SCP."
          scp root@10.200.50.1:~/source/dumps/* .
          echo ": turning off VPN."
          sudo wg-quick down wg-hector